--liquibase formatted sql

--changeset derkachev:0.1
CREATE TABLE cat
(
    id               BIGINT generated by default as identity primary key,
    breed            VARCHAR(20),
    name             VARCHAR(20),
    year_of_birthday INT,
    description      VARCHAR

);
CREATE TABLE dog
(
    id               BIGINT generated by default as identity primary key,
    breed            VARCHAR(20),
    name             VARCHAR(20),
    year_of_birthday INT,
    description      VARCHAR

);
CREATE TABLE users
(
    id      BIGINT generated by default as identity primary key,
    chat_id BIGINT NOT NULL UNIQUE,
    phone   INT
);
CREATE TABLE requests_for_feedback
(
    id             BIGINT generated by default as identity primary key,
    chat_id        BIGINT    NOT NULL,
    name           VARCHAR(20),
    task_date_time TIMESTAMP NOT NULL,
    phone          VARCHAR(20),
    active         BOOLEAN

);
