--liquibase formatted sql

--changeset derkachev:0
CREATE TABLE users
(
    id      BIGINT generated by default as identity primary key,
    chat_id BIGINT NOT NULL UNIQUE,
    phone   INT
);
CREATE TABLE requests_for_feedback
(
    id             BIGINT generated by default as identity primary key,
    chat_id        BIGINT    NOT NULL,
    name           VARCHAR(20),
    task_date_time TIMESTAMP NOT NULL,
    phone          VARCHAR(20)

);