package com.example.telegrambotshelter.handlerMain;

public enum BotState {
    SHOW_MAIN_MENU,
    SHOW_INFO_MENU,
    CALL_VOLUNTEER,
    SHOW_CAT_SHELTER_MENU,
    SHOW_DOG_SHELTER_MENU,
    INFO_CAT_SHELTER,
    INFO_DOG_SHELTER,
    TAKE_DOG,
    TAKE_CAT,
    SEND_REPORT_CAT,
    SEND_REPORT_DOG,
    CAT_SHELTER_SECURITY,
    DOG_SHELTER_SECURITY,
    INFO_MENU_CAT_SHELTER,
    INFO_MENU_DOG_SHELTER,
    CAT_SHELTER_ADDRESS,
    DOG_SHELTER_ADDRESS,
    DOG_SHELTER_RULES,
    CAT_SHELTER_RULES,
    CALL_BACK_CAT_SHELTER,
    CALL_BACK_DOG_SHELTER,
    VALIDATE_PHONE
}
